//
//  Font Size.swift
//  MMBS Arowana
//
//  Created by Ibrahim Aziz Tejokusumo on 9/5/15.
//  Copyright (c) 2015 Ibrahim Aziz Tejokusumo. All rights reserved.
//


// IMPORT

import Foundation
import UIKit


// GENERAL

public let FONTSIZE_TINY : CGFloat = 9
public let FONTSIZE_SMALL : CGFloat = 10
public let FONTSIZE_MEDIUM : CGFloat = 11
public let FONTSIZE_BIG : CGFloat = 12
public let FONTSIZE_LARGE : CGFloat = 14
public let FONTSIZE_HUGE : CGFloat = 18
public let FONTSIZE_TALL : CGFloat = 21
public let FONTSIZE_ENORMOUS : CGFloat = 36


// NAVIGATION

public let FONTSIZE_NAVIGATION_MENU : CGFloat = FONTSIZE_BIG
public let FONTSIZE_NAVIGATION_LOGIN : CGFloat = FONTSIZE_HUGE


// USER

public let FONTSIZE_USER_HEADER : CGFloat = FONTSIZE_HUGE
public let FONTSIZE_USER_DETAIL : CGFloat = FONTSIZE_MEDIUM
public let FONTSIZE_USER_NAME : CGFloat = FONTSIZE_BIG
public let FONTSIZE_USER_SETTING : CGFloat = FONTSIZE_SMALL


// HEADER

public let FONTSIZE_LOGIN_TITLE : CGFloat = FONTSIZE_ENORMOUS
public let FONTSIZE_HEADER_TITLE : CGFloat = FONTSIZE_ENORMOUS
public let FONTSIZE_HEADER_DESCRIPTION : CGFloat = FONTSIZE_SMALL


// GUIDE

public let FONTSIZE_GUIDE_STEP : CGFloat = FONTSIZE_TALL
public let FONTSIZE_GUIDE_DETAIL : CGFloat = FONTSIZE_SMALL


// PLAN

public let FONTSIZE_PLAN_TITLE : CGFloat = FONTSIZE_MEDIUM
public let FONTSIZE_PLAN_CONVERSATION : CGFloat = FONTSIZE_MEDIUM


// TABLE

public let FONTSIZE_TABLE_TITLE : CGFloat = FONTSIZE_HUGE
public let FONTSIZE_TABLE_CONTENT : CGFloat = FONTSIZE_LARGE


// LIST

public let FONTSIZE_LIST_HEADER : CGFloat = FONTSIZE_LARGE
public let FONTSIZE_LIST_DETAIL : CGFloat = FONTSIZE_MEDIUM


// LABEL

public let FONTSIZE_FORM_FIELD : CGFloat = FONTSIZE_MEDIUM
public let FONTSIZE_FORM_TITLE : CGFloat = FONTSIZE_LARGE


// INPUT

public let FONTSIZE_FORM_INPUT : CGFloat = FONTSIZE_MEDIUM


// BUTTON

public let FONTSIZE_FORM_BUTTON:CGFloat = FONTSIZE_MEDIUM


// FOOTER

public let FONTSIZE_FOOTER_HEADER : CGFloat = FONTSIZE_MEDIUM
public let FONTSIZE_FOOTER_DETAIL : CGFloat = FONTSIZE_SMALL